# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dixon\Projects\sqlpy\tabledata.ui'
#
# Created: Mon Feb 18 22:32:04 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(707, 300)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.wToolbar = QtGui.QWidget(Form)
        self.wToolbar.setStyleSheet(_fromUtf8("QWidget {\n"
"background: #d2d9e2;\n"
"}"))
        self.wToolbar.setObjectName(_fromUtf8("wToolbar"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.wToolbar)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bSaveChanges = QtGui.QToolButton(self.wToolbar)
        self.bSaveChanges.setEnabled(False)
        self.bSaveChanges.setMinimumSize(QtCore.QSize(24, 24))
        self.bSaveChanges.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSaveChanges.setIcon(icon)
        self.bSaveChanges.setAutoRaise(True)
        self.bSaveChanges.setObjectName(_fromUtf8("bSaveChanges"))
        self.horizontalLayout_3.addWidget(self.bSaveChanges)
        self.bRemoveSelectedRows = QtGui.QToolButton(self.wToolbar)
        self.bRemoveSelectedRows.setMinimumSize(QtCore.QSize(24, 24))
        self.bRemoveSelectedRows.setMaximumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/table_row_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRemoveSelectedRows.setIcon(icon1)
        self.bRemoveSelectedRows.setAutoRaise(True)
        self.bRemoveSelectedRows.setObjectName(_fromUtf8("bRemoveSelectedRows"))
        self.horizontalLayout_3.addWidget(self.bRemoveSelectedRows)
        self.bDiscardChanges = QtGui.QToolButton(self.wToolbar)
        self.bDiscardChanges.setEnabled(False)
        self.bDiscardChanges.setMinimumSize(QtCore.QSize(24, 24))
        self.bDiscardChanges.setMaximumSize(QtCore.QSize(24, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDiscardChanges.setIcon(icon2)
        self.bDiscardChanges.setAutoRaise(True)
        self.bDiscardChanges.setObjectName(_fromUtf8("bDiscardChanges"))
        self.horizontalLayout_3.addWidget(self.bDiscardChanges)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bRefresh = QtGui.QToolButton(self.wToolbar)
        self.bRefresh.setMinimumSize(QtCore.QSize(24, 24))
        self.bRefresh.setMaximumSize(QtCore.QSize(24, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/table_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRefresh.setIcon(icon3)
        self.bRefresh.setAutoRaise(True)
        self.bRefresh.setObjectName(_fromUtf8("bRefresh"))
        self.horizontalLayout_3.addWidget(self.bRefresh)
        self.ckLimit = QtGui.QCheckBox(self.wToolbar)
        self.ckLimit.setObjectName(_fromUtf8("ckLimit"))
        self.horizontalLayout_3.addWidget(self.ckLimit)
        self.label_5 = QtGui.QLabel(self.wToolbar)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.iLimit = QtGui.QSpinBox(self.wToolbar)
        self.iLimit.setMaximum(1000000)
        self.iLimit.setProperty(_fromUtf8("value"), 1000)
        self.iLimit.setObjectName(_fromUtf8("iLimit"))
        self.horizontalLayout_3.addWidget(self.iLimit)
        self.verticalLayout.addWidget(self.wToolbar)
        self.twGrid = QtGui.QTableView(Form)
        self.twGrid.setStyleSheet(_fromUtf8("QTableView::item::selected {\n"
"background: #dddceb;\n"
"}"))
        self.twGrid.setAlternatingRowColors(True)
        self.twGrid.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twGrid.setSortingEnabled(True)
        self.twGrid.setObjectName(_fromUtf8("twGrid"))
        self.verticalLayout.addWidget(self.twGrid)
        self.tTable = QtGui.QPlainTextEdit(Form)
        self.tTable.setObjectName(_fromUtf8("tTable"))
        self.verticalLayout.addWidget(self.tTable)
        self.widget = QtGui.QWidget(Form)
        self.widget.setStyleSheet(_fromUtf8("QLabel {\n"
"color: #fff;\n"
"}"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lDatabase = QtGui.QLabel(self.widget)
        self.lDatabase.setObjectName(_fromUtf8("lDatabase"))
        self.horizontalLayout.addWidget(self.lDatabase)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lTable = QtGui.QLabel(self.widget)
        self.lTable.setObjectName(_fromUtf8("lTable"))
        self.horizontalLayout.addWidget(self.lTable)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.actionExportData = QtGui.QAction(Form)
        self.actionExportData.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/application_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportData.setIcon(icon4)
        self.actionExportData.setObjectName(_fromUtf8("actionExportData"))
        self.actionCopy_Data = QtGui.QAction(Form)
        self.actionCopy_Data.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/table_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy_Data.setIcon(icon5)
        self.actionCopy_Data.setObjectName(_fromUtf8("actionCopy_Data"))
        self.actionInsert_Row = QtGui.QAction(Form)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/table_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert_Row.setIcon(icon6)
        self.actionInsert_Row.setObjectName(_fromUtf8("actionInsert_Row"))
        self.actionDuplicateRow = QtGui.QAction(Form)
        self.actionDuplicateRow.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/table_multiple.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDuplicateRow.setIcon(icon7)
        self.actionDuplicateRow.setObjectName(_fromUtf8("actionDuplicateRow"))
        self.actionSave_changes = QtGui.QAction(Form)
        self.actionSave_changes.setEnabled(False)
        self.actionSave_changes.setIcon(icon)
        self.actionSave_changes.setObjectName(_fromUtf8("actionSave_changes"))
        self.actionDelete_Row = QtGui.QAction(Form)
        self.actionDelete_Row.setIcon(icon1)
        self.actionDelete_Row.setObjectName(_fromUtf8("actionDelete_Row"))
        self.actionDiscard_changes = QtGui.QAction(Form)
        self.actionDiscard_changes.setEnabled(False)
        self.actionDiscard_changes.setIcon(icon2)
        self.actionDiscard_changes.setObjectName(_fromUtf8("actionDiscard_changes"))
        self.actionRefresh = QtGui.QAction(Form)
        self.actionRefresh.setIcon(icon3)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.bSaveChanges.setStatusTip(QtGui.QApplication.translate("Form", "Save changes", None, QtGui.QApplication.UnicodeUTF8))
        self.bRemoveSelectedRows.setStatusTip(QtGui.QApplication.translate("Form", "Delete selected rows", None, QtGui.QApplication.UnicodeUTF8))
        self.bDiscardChanges.setStatusTip(QtGui.QApplication.translate("Form", "Discard changes", None, QtGui.QApplication.UnicodeUTF8))
        self.bRefresh.setStatusTip(QtGui.QApplication.translate("Form", "Refesh data", None, QtGui.QApplication.UnicodeUTF8))
        self.ckLimit.setText(QtGui.QApplication.translate("Form", "Limit rows", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "# of rows", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.lDatabase.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Table:", None, QtGui.QApplication.UnicodeUTF8))
        self.lTable.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportData.setText(QtGui.QApplication.translate("Form", "Export as ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_Data.setText(QtGui.QApplication.translate("Form", "Copy Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsert_Row.setText(QtGui.QApplication.translate("Form", "Insert new row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicateRow.setText(QtGui.QApplication.translate("Form", "Duplicate Current Row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicateRow.setToolTip(QtGui.QApplication.translate("Form", "Duplicate Current Row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_changes.setText(QtGui.QApplication.translate("Form", "Save changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Row.setText(QtGui.QApplication.translate("Form", "Delete selected row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiscard_changes.setText(QtGui.QApplication.translate("Form", "Discard changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
